//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configuration.DkimSigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Configuration.DkimSigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIME body could not be located, so DKIM signing was skipped..
        /// </summary>
        internal static string DkimSigningRoutingAgent_MimeBodyNotFound {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgent_MimeBodyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PEM-encoded RSA Private Key is not specified, so DKIM signing was skipped..
        /// </summary>
        internal static string DkimSigningRoutingAgent_NoKey {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgent_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing a mail item according to DKIM failed with an exception. Check the logged exception for details..
        /// </summary>
        internal static string DkimSigningRoutingAgent_SignFailed {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgent_SignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration for Exchange Dkim Agent is not defined..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadDkimConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadDkimConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain was not found in the configuration file or is blank. Check the value of the &apos;DefaultDkimSigner_Domain&apos; key under the &lt;appSettings&gt; section..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadDkimDomainConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadDkimDomainConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PEM-encoded private RSA key was not found in the configuration file or is blank. Check the value of the &apos;DefaultDkimSigner_PrivateKey&apos; key in the &lt;appSettings&gt; section..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadDkimPrivateKeyConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadDkimPrivateKeyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector was not found in the configuration file or is blank. Check the value of the &apos;DefaultDkimSigner_Selector&apos; key under &lt;appSettings&gt;..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadDkimSelectorConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadDkimSelectorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log level is not defined or is invalid..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadLogLevel {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to load the specified DKIM algorithm..
        /// </summary>
        internal static string MainWindows_BadDkimAlgorithmConfig {
            get {
                return ResourceManager.GetString("MainWindows_BadDkimAlgorithmConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to load the specified DKIM canonicalization body format. The &quot;Simple&quot; format has been selected..
        /// </summary>
        internal static string MainWindows_BadDkimCanonicalizationBodyConfig {
            get {
                return ResourceManager.GetString("MainWindows_BadDkimCanonicalizationBodyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to load the specified DKIM canonicalization header format. The &quot;Simple&quot; format has been selected..
        /// </summary>
        internal static string MainWindows_BadDkimCanonicalizationHeaderConfig {
            get {
                return ResourceManager.GetString("MainWindows_BadDkimCanonicalizationHeaderConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log level is not defined or is invalid. The &quot;information&quot; log level have been selected..
        /// </summary>
        internal static string MainWindows_BadLogLevel {
            get {
                return ResourceManager.GetString("MainWindows_BadLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded key is not in the proper DER format..
        /// </summary>
        internal static string RSACryptHelper_BadDerFormat {
            get {
                return ResourceManager.GetString("RSACryptHelper_BadDerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded key is not in the proper PEM format..
        /// </summary>
        internal static string RSACryptHelper_BadPemFormat {
            get {
                return ResourceManager.GetString("RSACryptHelper_BadPemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded key is not in the proper XML format..
        /// </summary>
        internal static string RSACryptHelper_BadXmlFormat {
            get {
                return ResourceManager.GetString("RSACryptHelper_BadXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded key is not in a proper format..
        /// </summary>
        internal static string RSACryptHelper_UnknownFormat {
            get {
                return ResourceManager.GetString("RSACryptHelper_UnknownFormat", resourceCulture);
            }
        }
    }
}
