//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DkimSigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.DkimSigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded key is not in the proper DER format..
        /// </summary>
        internal static string CryptHelper_BadDerFormat {
            get {
                return ResourceManager.GetString("CryptHelper_BadDerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded key is not in the proper PEM format..
        /// </summary>
        internal static string CryptHelper_BadPemFormat {
            get {
                return ResourceManager.GetString("CryptHelper_BadPemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded key is not in the proper XML format..
        /// </summary>
        internal static string CryptHelper_BadXmlFormat {
            get {
                return ResourceManager.GetString("CryptHelper_BadXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded key is not in a proper format..
        /// </summary>
        internal static string CryptHelper_UnknownFormat {
            get {
                return ResourceManager.GetString("CryptHelper_UnknownFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIME body could not be located, so DKIM signing was skipped..
        /// </summary>
        internal static string DkimSigningRoutingAgent_MimeBodyNotFound {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgent_MimeBodyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PEM-encoded RSA Private Key is not specified, so DKIM signing was skipped..
        /// </summary>
        internal static string DkimSigningRoutingAgent_NoKey {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgent_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing a mail item according to DKIM failed with an exception. Check the logged exception for details..
        /// </summary>
        internal static string DkimSigningRoutingAgent_SignFailed {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgent_SignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm specified in the configuration file could not be parsed. Check the value of the &apos;DefaultDkimSigner_Algorithm&apos; key under &lt;appSettings&gt;. Currently accepted values are &apos;RsaSha1&apos; (recommended) and &apos;RsaSha256&apos;..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadAlgorithmConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadAlgorithmConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  body canonicalization algorithm specified in the configuration file could not be parsed. Check the value of the &apos;DefaultDkimSigner_Algorithm&apos; key under &amp;lt;appSettings&amp;gt;. Currently accepted values are &apos;Simple&apos; (recommended) and &apos;Relaxed&apos;..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadCanonicalizationBodyConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadCanonicalizationBodyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  header canonicalization algorithm specified in the configuration file could not be parsed. Check the value of the &apos;DefaultDkimSigner_Algorithm&apos; key under &amp;lt;appSettings&amp;gt;. Currently accepted values are &apos;Simple&apos; (recommended) and &apos;Relaxed&apos;..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadCanonicalizationHeaderConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadCanonicalizationHeaderConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain was not found in the configuration file or is blank. Check the value of the &apos;DefaultDkimSigner_Domain&apos; key under the &lt;appSettings&gt; section..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadDomainConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadDomainConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PEM-encoded private RSA key was not found in the configuration file or is blank. Check the value of the &apos;DefaultDkimSigner_PrivateKey&apos; key in the &lt;appSettings&gt; section..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadPrivateKeyConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadPrivateKeyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector was not found in the configuration file or is blank. Check the value of the &apos;DefaultDkimSigner_Selector&apos; key under &lt;appSettings&gt;..
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadSelectorConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadSelectorConfig", resourceCulture);
            }
        }
    }
}
